[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist/"

[functions]
  directory = "backend/app_netlify/"

[functions."*"] 
  runtime = "python3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200