[build]
  command = "cd frontend && npm install && npm run build" # Build frontend: cd into frontend, install, then build
  publish = "frontend/dist/"              # Path to the built frontend assets, from the repo root.

# Settings for Netlify Functions (your Python backend)
[functions]
  directory = "backend/app_netlify/"     # Path to your Netlify functions, from the repo root.

# Redirects and Rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html" # Serve index.html from the root of the 'publish' directory
  status = 200